### ISSUE TITLE
Already usable?

### ISSUE THREAD

**Issue by hernandev** [johnhearfield/flarum-ext-oauth-google#1]
Hi, i just found this repo, i need to integrate google login, is this plugin already working?

**Comment by johnhearfield** [comment]
It's usable, and can be found on Packagist: https://packagist.org/packages/johnhearfield/flarum-ext-oauth-google

I'm going to work up a Readme later on, and test it with/without the Hosted Domain. The Hosted Domain field is for limiting auth based on a Google-apps business email
Read about that here: https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters
